### PR TITLE
Adjust backedge insertion

### LINKED ISSUE #31: Structural analysis can see invalid world age after refresh
```
ERROR: invalid age range update
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:44
  [2] WorldWithRange
    @ ./../usr/share/julia/Compiler/src/inferencestate.jl:253 [inlined]
  [3] Compiler.IRInterpretationState(interp::DAECompiler.StructuralRefiner, spec_info::Compiler.SpecInfo, ir::Compiler.IRCode, mi::Core.MethodInstance, argtypes::Vector{Any}, world::UInt64, min_world::UInt64, max_world::UInt64)
    @ Compiler ./../usr/share/julia/Compiler/src/inferencestate.jl:861
  [4] _structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler2/src/analysis/structural.jl:159
  [5] structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler2/src/analysis/structural.jl:26
```

### PR DESCRIPTION
**Pull request by Keno**
Together with https://github.com/JuliaLang/julia/pull/58390 fixes https://github.com/CedarEDA/DAECompiler.jl/issues/31.

@serenity4 we may need a better test for the invalidation of the factory method. It was broken, but the existing tests didn't catch that.

### CODE REVIEW

File: src/transform/common.jl [hunk 1]
```diff
@@ -65,11 +65,11 @@ end
...
 function cache_dae_ci!(old_ci, src, debuginfo, abi, owner)
     mi = old_ci.def
-    edges = Core.svec(mi)
+    edges = Core.svec(old_ci)
     daef_ci = CodeInstance(abi === nothing ? old_ci.def : Core.ABIOverride(abi, old_ci.def), owner, Tuple, Union{}, nothing, src, Int32(0),
-        UInt(1)#=ci.min_world=#, old_ci.max_world, old_ci.ipo_purity_bits,
+        old_ci.min_world, old_ci.max_world, old_ci.ipo_purity_bits,
         nothing, debuginfo, edges)
-    ccall(:jl_method_instance_add_backedge, Cvoid, (Any, Any, Any), mi, nothing, daef_ci)
+    Compiler.store_backedges(daef_ci, edges)
```
Comment (serenity4) [inline src/transform/common.jl:72]: `store_backedges`  will [ignore](https://github.com/JuliaLang/julia/blob/2a5cfee2807add7babf00ddd93da505e2cce5719/Compiler/src/typeinfer.jl#L752) a few `CodeInstance`s that we generate, that's why I used `jl_method_instance_add_backedge`. We might want to remove this check in Compiler instead, but I don't know what the implications are/what were the motivations to have it in the first place.
```suggestion
    ccall(:jl_method_instance_add_backedge, Cvoid, (Any, Any, Any), old_ci, nothing, daef_ci)
```

Comment (serenity4) [reply src/transform/common.jl:72]: (this should be picked up by tests)

Comment (Keno) [reply src/transform/common.jl:72]: I don't think we're using any CodeInstances that don't have an associated method.

Comment (serenity4) [reply src/transform/common.jl:72]: I don't recall exactly what we had, but this check did trigger for some. That's most likely what [broke the tests](https://github.com/CedarEDA/DAECompiler.jl/actions/runs/14982833801/job/42090720227?pr=32#step:6:850).

**Comment by serenity4** [comment]
Thanks for the fix. I managed to reproduce the issue once, but this seems either non-deterministic or evaluation order-dependent, and now I can't reproduce it.

File: src/transform/common.jl (hunk 1 above)
Comment (Keno) [reply src/transform/common.jl:72]: It's possible that check in base needs to use a `get_ci_mi(ci).def` instead so that our ABI override code instances work properly, but I didn't think we put those into `edges`

**Comment by serenity4** [comment]
It does depend on evaluation order. If I execute the invalidation tests first, then I can't observe the bug, no matter how I invalidate/reexecute code.

The test suite broke on latest nightly, and I get the invalid world age error only after triggering the error and then doing `refresh()`. If these observations are correct, I don't think we can test that reliably.

<details>

<summary>Stacktrace for nightly failure</summary>

```julia
ERROR: LoadError: FieldError: type String has no field `extended_rt`; String has no fields at all.
Stacktrace:
  [1] getproperty(x::String, f::Symbol)
    @ Base ./Base_compiler.jl:57
  [2] abstract_eval_invoke_inst(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, irsv::Compiler.IRInterpretationState)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/refiner.jl:54
  [3] reprocess_instruction!(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, idx::Int64, bb::Int64, irsv::Compiler.IRInterpretationState)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:168
  [4] (::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode})(inst::Compiler.Instruction, lstmt::Int64, bb::Int64)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:364
  [5] scan!(callback::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode}, scanner::Compiler.BBScanner, forwards_only::Bool)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:286
  [6] ir_abstract_constant_propagation(interp::DAECompiler.StructuralRefiner, irsv::Compiler.IRInterpretationState; externally_refined::BitSet)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:332
  [7] _structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:160
  [8] structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:26
  [9] abstract_eval_invoke_inst(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, irsv::Compiler.IRInterpretationState)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/refiner.jl:52
 [10] reprocess_instruction!(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, idx::Int64, bb::Int64, irsv::Compiler.IRInterpretationState)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:168
 [11] (::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode})(inst::Compiler.Instruction, lstmt::Int64, bb::Int64)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:364
 [12] scan!(callback::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode}, scanner::Compiler.BBScanner, forwards_only::Bool)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:286
 [13] ir_abstract_constant_propagation(interp::DAECompiler.StructuralRefiner, irsv::Compiler.IRInterpretationState; externally_refined::BitSet)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:332
 [14] _structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:160
 [15] structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:26
 [16] abstract_eval_invoke_inst(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, irsv::Compiler.IRInterpretationState)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/refiner.jl:52
 [17] reprocess_instruction!(interp::DAECompiler.StructuralRefiner, inst::Compiler.Instruction, idx::Int64, bb::Int64, irsv::Compiler.IRInterpretationState)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:168
 [18] (::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode})(inst::Compiler.Instruction, lstmt::Int64, bb::Int64)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:364
 [19] scan!(callback::Compiler.var"#217#218"{BitSet, DAECompiler.StructuralRefiner, Compiler.IRInterpretationState, Compiler.var"#check_ret!#216"{Vector{Int64}}, BitSet, Compiler.TwoPhaseDefUseMap, Compiler.IRCode}, scanner::Compiler.BBScanner, forwards_only::Bool)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:286
 [20] ir_abstract_constant_propagation(interp::DAECompiler.StructuralRefiner, irsv::Compiler.IRInterpretationState; externally_refined::BitSet)
    @ Compiler ~/.julia/packages/Compiler/X1WCU/src/ssair/irinterp.jl:332
 [21] _structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:160
 [22] structural_analysis!(ci::Core.CodeInstance, world::UInt64)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/analysis/structural.jl:26
 [23] factory_gen(world::UInt64, source::Method, _gen::Any, settings::Type, fT::Any)
    @ DAECompiler ~/.julia/dev/DAECompiler/src/interface.jl:32
 [24] get_concrete_problem(prob::DAECompiler.DAECProblem{typeof(Main.ipo.sin2!), Tuple{Pair{Int64, Float64}, Pair{Int64, Float64}}, Nothing, Tuple{Float64, Float64}, @Kwargs{}}, isadaptive::Bool; kwargs::@Kwargs{u0::Nothing, p::Missing})
    @ DAECompiler ~/.julia/dev/DAECompiler/src/problem_interface.jl:31
 [25] get_concrete_problem
    @ ~/.julia/dev/DAECompiler/src/problem_interface.jl:30 [inlined]
 [26] solve_up(prob::DAECompiler.DAECProblem{typeof(Main.ipo.sin2!), Tuple{Pair{Int64, Float64}, Pair{Int64, Float64}}, Nothing, Tuple{Float64, Float64}, @Kwargs{}}, sensealg::Nothing, u0::Nothing, p::Missing, args::Sundials.IDA{:Dense, Nothing, Nothing}; kwargs::@Kwargs{})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/3HGYN/src/solve.jl:1193
 [27] solve_up
    @ ~/.julia/packages/DiffEqBase/3HGYN/src/solve.jl:1177 [inlined]
 [28] solve(prob::DAECompiler.DAECProblem{typeof(Main.ipo.sin2!), Tuple{Pair{Int64, Float64}, Pair{Int64, Float64}}, Nothing, Tuple{Float64, Float64}, @Kwargs{}}, args::Sundials.IDA{:Dense, Nothing, Nothing}; sensealg::Nothing, u0::Nothing, p::Nothing, wrap::Val{true}, kwargs::@Kwargs{})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/3HGYN/src/solve.jl:1089
 [29] solve(prob::DAECompiler.DAECProblem{typeof(Main.ipo.sin2!), Tuple{Pair{Int64, Float64}, Pair{Int64, Float64}}, Nothing, Tuple{Float64, Float64}, @Kwargs{}}, args::Sundials.IDA{:Dense, Nothing, Nothing})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/3HGYN/src/solve.jl:1079
 [30] top-level scope
    @ ~/.julia/dev/DAECompiler/test/ipo.jl:44
```

</details>

**Comment by Keno** [comment]
> It does depend on evaluation order. If I execute the invalidation tests first, then I can't observe the bug, no matter how I invalidate/reexecute code.

There needs to be an old CodeInstance for the same method in the cache. It should be reproducible by running a test from `ipo.jl`, then doing `refresh()` and then rerunning the same test without re-defining the method. I'm not seeing the failure you posted, but I can take a look later or tomorrow.

File: src/transform/common.jl (hunk 1 above)
Comment (serenity4) [reply src/transform/common.jl:72]: The check is for callers not edges, which are the ABI override code instances.

Comment (Keno) [reply src/transform/common.jl:72]: Ah. Yes, submit a PR to base to put in the get_ci_mi then

**Comment by serenity4** [comment]
I can't reproduce with the non-erroring tests, there seems to be a correlation with the new failure mode and the invalid world range error path. Method redefinition doesn't seem to have any effect for me.

**Comment by serenity4** [comment]
Ah, I still had https://github.com/CedarEDA/Compiler.jl in my manifest instead of https://github.com/JuliaLang/BaseCompiler.jl. The "new error on nightly" was a false alert, it's fixed by using BaseCompiler.

**Comment by serenity4** [comment]
I can't reproduce it at all anymore. I'll be happy to add a test for it if you manage to get a reproducer.

File: src/transform/common.jl (hunk 1 above)
Comment (serenity4) [reply src/transform/common.jl:72]: PR: https://github.com/JuliaLang/julia/pull/58394
I confirmed that this change allows `store_backedges` to work correctly with our `CodeInstance`s, instead of needing to call `jl_method_instance_add_backedge` manually.

**Review by serenity4 — APPROVED** [review]
